import React, { useState } from "react";
import WorkCard from "./WorkCard";
import "../styles/Works.css";
import { v4 as uuidv4 } from 'uuid';

function Works() {
  const initialWorkExperience = {
    companyName: "Fancy Company",
    companyLocation: "Los Angeles, United States",
    startDate: "Jan 2022",
    endDate: "Jul 2023",
    role: "Your Role, e.g: IT Support",
    roleDescription:
      "Summary of your role. e.g: Internet node administrator, technical support, Internet equipment configuration, network cabling, basic telephony knowledge, customer service, advice, billing...",
  };

  const [workExperiences, setWorkExperiences] = useState([initialWorkExperience]);

  const addWorkExperience = () => {
    setWorkExperiences((prevExperiences) => [
      ...prevExperiences,
      { ...prevExperiences[prevExperiences.length - 1], id: uuidv4() }, // Add a unique id
    ]);
  };

  const deleteLastWorkExperience = () => {
    if (workExperiences.length > 1) {
      setWorkExperiences((prevExperiences) =>
        prevExperiences.slice(0, -1)
      );
    }
  };

  return (
    <div>
      <h3>Work Experience</h3>
      <hr />
      {workExperiences.map((work) => (
        <WorkCard
          key={work.id} // Use the id generated by uuidv4 as the key
          companyName={work.companyName}
          companyLocation={work.companyLocation}
          startDate={work.startDate}
          endDate={work.endDate}
          role={work.role}
          roleDescription={work.roleDescription}
        />
      ))}
      <div className="add-del-work-btns-container">
        <button className="add-del-work-btn" onClick={addWorkExperience}>Add Experience</button>
        <button className="add-del-work-btn" onClick={deleteLastWorkExperience}>Remove Experience</button>
      </div>
    </div>
  );
}

export default Works;
